version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: proselyte-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: proselyte
      MYSQL_PASSWORD: proselyte
      MYSQL_ROOT_HOST: '%'

  spring-app:
    image: spring-security-app
    depends_on:
      - db
    ports:
      - '8080:8080'
    restart: always
