spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: proselyte
    password: proselyte
    url: jdbc:mysql://localhost:3306/proselyte
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
file:
  storage: 'src/main/resources/storage'

jwt:
  header: Authorization
  secret: proselyte
  expiration: 604800

